CREATE DATABASE IF NOT EXISTS PRODUCTION_ELT;

USE DATABASE PRODUCTION_ELT;

CREATE SCHEMA IF NOT EXISTS RAW;

CREATE WAREHOUSE IF NOT EXISTS ELT_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE ELT_WH;
USE SCHEMA RAW;