name: Production ELT CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  python-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Compile Python code
        run: python -m compileall ingestion scripts

    dbt-checks:
     runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          pip install dbt-core==1.12.3
          pip install dbt-snowflake==1.12.0

      - name: Parse dbt project
        working-directory: productioneltplatform
        run: dbt parse --no-partial-parse